#!/bin/bash

set -e

from=$(dirname "$(readlink -f "$0")")
to="$HOME/.config/nvim"
rm -rf "$HOME/.cache/nvim"
rm -rf "$HOME/.local/share/nvim"
rm -rf "$to" 2>/dev/null || true

mkdir -p "$to"
git -C "$to" clone -b main --depth 1 https://github.com/NvChad/NvChad.git .
ln -s "$from/ftplugin" "$to/"
ln -s "$from/lua/custom" "$to/lua/"
ln -s "$from/.luarc.json" "$to/"
ln -s "$from/coc-settings.json" "$to/"

# mkdir -p "$to/.local"
# sudo ln -s "$HOME/.local/share/nvim" "$to/.local/"

nvim
nvim +PackerSync

set +e
